#!/usr/bin/env bash

# This script deletes the network namespace for the given bot id

botid=$1

get_default_interface() {
    local interface=""

    if [[ -n "${CATHOOK_NET_INTERFACE:-}" ]]; then
        printf '%s\n' "$CATHOOK_NET_INTERFACE"
        return
    fi

    interface="$(ip -o -4 route get "${CATHOOK_NET_PROBE_HOST:-1.1.1.1}" 2>/dev/null | awk '
        {
            for (i = 1; i <= NF; i++) {
                if ($i == "dev" && (i + 1) <= NF) {
                    print $(i + 1)
                    exit
                }
            }
        }')"

    if [[ -n "$interface" ]]; then
        printf '%s\n' "$interface"
        return
    fi

    ip -o -4 route show default 2>/dev/null | awk '
        {
            for (i = 1; i <= NF; i++) {
                if ($i == "dev" && (i + 1) <= NF) {
                    print $(i + 1)
                    exit
                }
            }
        }'
}

NS="catbotns$botid"
VETH="veth$botid"
VPEER_ADDR="10.200.$botid.2"
INTERFACE="$(get_default_interface)"

if [[ $EUID -ne 0 ]]; then
    echo "You must be root to run this script"
    exit 1
fi

ip netns delete "$NS"
ip link del "$VETH"

if [[ -n "$INTERFACE" ]]; then
    iptables -t nat -D POSTROUTING -s ${VPEER_ADDR}/24 -o "$INTERFACE" -j MASQUERADE
    iptables -D FORWARD -i "$INTERFACE" -o ${VETH} -j ACCEPT
    iptables -D FORWARD -o "$INTERFACE" -i ${VETH} -j ACCEPT
fi
